image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

variables:
  KOHA_PATH: $CI_PROJECT_DIR

build-debian-files:
  stage: build
  script:
    - source docker-compose/docker-compose.env
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml build koha_patched
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml up -d --force-recreate --no-deps koha_patched
