image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  KOHAPATH: $CI_PROJECT_DIR

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose


build-debian-files:
  stage: build
  script:
    - source docker-compose/docker-compose.env
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml build koha_patched
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml up -d --force-recreate --no-deps koha_patched
