image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  KOHAPATH: $CI_PROJECT_DIR
  COMPOSE_CMD: docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add git python python-dev py-pip build-base
  - pip install docker-compose

build-debian-files:
  stage: build
  script:
    - source docker-compose/docker-compose.env
    - $COMPOSE_CMD build koha_patched
    - $COMPOSE_CMD up -d --force-recreate --no-deps koha_patched
    - $COMPOSE_CMD logs -f --no-color koha_patched
  artifacts:
    paths:
      - debian
    expire_in: 1 week
