image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay
  KOHAPATH: $CI_PROJECT_DIR
  COMPOSE_CMD: docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml -v $CI_PROJECT_DIR/koha-patched/debian:/debian
  DEBIAN_REPO_INCOMING: datatest.deichman.no:/var/www/datatest.deichman.no/repositories/koha/incoming/
  DEBIAN_REPO_DIR: /var/www/datatest.deichman.no/repositories/koha

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add git rsync openssh python python-dev py-pip build-base
  - pip install docker-compose
  # deploy settings
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_debian_files:
  stage: build
  script:
    - source docker-compose/docker-compose.env
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml build koha_patched
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml -v $(pwd)/koha-patched/debian:/debian up -d --force-recreate --no-deps koha_patched
    - docker-compose -f docker-compose/common.yml -f docker-compose/patched.yml logs -f --no-color koha_patched
  artifacts:
    paths:
      - koha-patched/debian
    expire_in: 1 week

# Deploy to datatest.deichman.no
deploy_debian_files:
  stage: deploy
  script:
    - echo "$STAGING_PRIVATE_KEY" > ~/.ssh/id_rsa
    - rsync -av --delete $CI_PROJECT_DIR/koha-patched/debian/ $DEBIAN_REPO_INCOMING
    # drop old repo
    - ssh jenkins@datatest.deichman.no "docker run --rm --name aptly_docker -v $DEBIAN_REPO_DIR:/aptly digibib/aptly:latest
      aptly snapshot drop koha-patched"
    # drop old snapshot
    - ssh jenkins@datatest.deichman.no "docker run --rm --name aptly_docker -v $DEBIAN_REPO_DIR:/aptly digibib/aptly:latest
      aptly snapshot drop koha-patched
    # add packages from incoming
    - ssh jenkins@datatest.deichman.no "docker run --rm --name aptly_docker -v $DEBIAN_REPO_DIR:/aptly digibib/aptly:latest
      aptly repo include -keyring=6DDE02B2 -accept-unsigned=true -repo=deichmankoha -architectures=amd64 /aptly/incoming"
    # create new repo
    - ssh jenkins@datatest.deichman.no "docker run --rm --name aptly_docker -v $DEBIAN_REPO_DIR:/aptly digibib/aptly:latest
      aptly snapshot create -architectures=amd64 koha-patched from repo deichmankoha
    # publish
    - ssh jenkins@datatest.deichman.no "docker run --rm --name aptly_docker -v $DEBIAN_REPO_DIR:/aptly digibib/aptly:latest
      aptly publish snapshot -architectures=i386,amd64 -skip-signing=true koha-patched
