image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache make
  - apk add --no-cache py-pip
  - pip install docker-compose

build-debian-files:
  stage: build
  script:
   - KOHAENV=patched make rebuild logs-f-nocolor delete
