version: '2.1'
services:
  koha_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    container_name: koha_es
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - koha_esdata:/usr/share/elasticsearch/data
      - koha_esplugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  koha_esdata:
    driver: local
  koha_esplugins:
    driver: local

networks:
  backend:
    driver: bridge
