---
version: '2.1'

services:
  koha:
    build:
      context: "${KOHAPATH}/koha-patched"
      dockerfile: Dockerfile
      args: {}
    volumes:
      - ${KOHAPATH}/koha-patched/patches:/patches
      - ${KOHAPATH}/koha-patched/debian:/debian