---
version: '2.1'

services:
  koha:
    build:
      context: "${KOHAPATH}/koha-patched"
      dockerfile: Dockerfile
      args:
        KOHA_BUILD: "${KOHA_BUILD}"
    volumes:
      - ${KOHAPATH}/koha-patched/patches:/patches
      - ${KOHAPATH}/koha-patched/debian:/debian